import { Product, Category, Order, User, Promotion, Review } from '../../shared/types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-audio',
    name: 'Âm thanh & Loa',
    slug: 'am-thanh-loa',
    description: 'Trải nghiệm âm thanh trung thực chuẩn phòng thu với công nghệ chống ồn tiên tiến.',
    icon: 'Headphones',
    itemCount: 4,
    illustrationType: 'audio',
  },
  {
    id: 'cat-watches',
    name: 'Đồng hồ & Vòng đeo',
    slug: 'dong-ho-vong-deo',
    description: 'Chất liệu Titanium chuẩn hàng không vũ trụ và cảm biến đo chỉ số sinh trắc chính xác.',
    icon: 'Watch',
    itemCount: 3,
    illustrationType: 'watch',
  },
  {
    id: 'cat-workspace',
    name: 'Bàn làm việc & Ánh sáng',
    slug: 'ban-lam-viec-anh-sang',
    description: 'Kiến tạo không gian làm việc tối giản, công thái học và chuẩn thẩm mỹ Bắc Âu.',
    icon: 'Lamp',
    itemCount: 5,
    illustrationType: 'lamp',
  },
  {
    id: 'cat-accessories',
    name: 'Phụ kiện cao cấp',
    slug: 'phu-kien-cao-cap',
    description: 'Dock Thunderbolt, sạc GaN siêu nhanh và giải pháp kết nối hiệu năng đỉnh cao.',
    icon: 'Cpu',
    itemCount: 4,
    illustrationType: 'hub',
  },
  {
    id: 'cat-smarthome',
    name: 'Gia dụng thông minh',
    slug: 'gia-dung-thong-minh',
    description: 'Hệ sinh thái tự động hóa và an ninh chuẩn mực cho phong cách sống hiện đại.',
    icon: 'Home',
    itemCount: 2,
    illustrationType: 'camera',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    name: 'Tai nghe chống ồn AURA Studio Pro ANC',
    slug: 'tai-nghe-aura-studio-pro-anc',
    sku: 'AUR-HP-01',
    category: 'Âm thanh & Loa',
    price: 7890000,
    originalPrice: 8990000,
    discount: 12,
    rating: 4.9,
    reviewsCount: 142,
    stock: 28,
    description: 'Được chế tác từ nhôm nguyên khối hàng không và da protein cao cấp, AURA Studio Pro mang đến chất âm hi-res đỉnh cao, công nghệ khử ồn chủ động 40dB và thời lượng pin 45 giờ liên tục.',
    specs: {
      'Driver': '40mm Titanium Custom',
      'Chống ồn': 'Active Noise Cancelling 4 mic kép',
      'Pin': '45 giờ (ANC Bật)',
      'Kết nối': 'Bluetooth 5.4, aptX Lossless, Type-C 24bit/96kHz',
      'Trọng lượng': '248g',
    },
    features: [
      'Chất âm Hi-Res Studio đẳng cấp chuẩn audiophile',
      'Khử tiếng ồn thích ứng theo thời gian thực',
      'Đệm tai Memory Foam thoáng khí êm ái cả ngày',
      'Sạc nhanh 10 phút nghe 5 giờ',
    ],
    images: ['audio-1', 'audio-2', 'audio-3'],
    illustrationType: 'audio',
    badge: 'Bán chạy nhất',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    variants: {
      colors: ['Đen Titan Obsidian', 'Bạc Ánh Trăng Lunar', 'Xám Đậm Space Gray'],
    },
    createdAt: '2026-08-15T10:00:00Z',
    isActive: true,
  },
  {
    id: 'prod-02',
    name: 'Đồng hồ thông minh AURA Chrono Titanium Ultra',
    slug: 'dong-ho-aura-chrono-titanium-ultra',
    sku: 'AUR-WT-02',
    category: 'Đồng hồ & Vòng đeo',
    price: 11490000,
    originalPrice: 12990000,
    discount: 11,
    rating: 4.8,
    reviewsCount: 96,
    stock: 15,
    description: 'Vỏ Titanium Cấp 5 siêu bền, mặt kính Sapphire chống trầy tuyệt đối cùng màn hình LTPO AMOLED 2000 nits. Đồng hành cùng bạn trong mọi chuyến thám hiểm và theo dõi sức khỏe chuyên sâu.',
    specs: {
      'Chất liệu vỏ': 'Titanium Grade 5 siêu nhẹ',
      'Màn hình': '1.43 inch LTPO AMOLED, 2000 nits, Sapphire Glass',
      'Chống nước': '10ATM / 100m chuẩn thợ lặn',
      'Thời lượng pin': '14 ngày sử dụng tiêu chuẩn',
      'Cảm biến': 'ECG, SpO2 quang phổ kép, GPS tần số kép L1+L5',
    },
    features: [
      'Vỏ Titanium Cấp 5 bền bỉ chịu mọi điều kiện khắc nghiệt',
      'Đo điện tâm đồ ECG và cảnh báo nhịp tim bất thường',
      'GPS tần số kép định vị chuẩn xác từng mét',
      'Thời lượng pin vượt trội lên tới 14 ngày',
    ],
    images: ['watch-1', 'watch-2', 'watch-3'],
    illustrationType: 'watch',
    badge: 'Mới ra mắt',
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    variants: {
      colors: ['Titanium Tự Nhiên', 'Đen DLC Carbon', 'Vàng Cát Safari'],
    },
    createdAt: '2026-09-01T08:00:00Z',
    isActive: true,
  },
  {
    id: 'prod-03',
    name: 'Đèn bàn công thái học AURA Lumina Arc',
    slug: 'den-ban-aura-lumina-arc',
    sku: 'AUR-LP-03',
    category: 'Bàn làm việc & Ánh sáng',
    price: 2650000,
    originalPrice: 3100000,
    discount: 15,
    rating: 4.9,
    reviewsCount: 218,
    stock: 42,
    description: 'Kiệt tác chiếu sáng tối giản dành cho không gian làm việc chuyên nghiệp. Quang phổ ánh sáng tự nhiên Ra≥98 giảm mỏi mắt tuyệt đối, điều khiển cảm ứng không chạm và xoay đa trục mượt mà.',
    specs: {
      'Chỉ số hoàn màu': 'CRI Ra ≥ 98',
      'Nhiệt độ màu': '2700K - 6500K tùy biến',
      'Công suất': '18W LED Ultra-EyeCare',
      'Chất liệu': 'Nhôm Anodized 6063 cao cấp',
      'Điều khiển': 'Cảm biến không chạm & núm xoay kim loại vô cực',
    },
    features: [
      'Ánh sáng mô phỏng mặt trời tự nhiên không gây hại mắt',
      'Điều chỉnh độ sáng và nhiệt độ màu mượt mà',
      'Cần đèn nhôm công nghệ khớp quay thủy lực tĩnh âm',
      'Tích hợp cổng sạc Type-C PD 20W ở chân đế',
    ],
    images: ['lamp-1', 'lamp-2'],
    illustrationType: 'lamp',
    badge: 'Yêu thích',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    variants: {
      colors: ['Đen Mờ Matte Black', 'Bạc Nhôm Silver', 'Trắng Bắc Âu Arctic'],
    },
    createdAt: '2026-07-20T14:30:00Z',
    isActive: true,
  },
  {
    id: 'prod-04',
    name: 'Loa không dây cao cấp AURA Horizon Hi-Fi 360°',
    slug: 'loa-khong-day-aura-horizon-hi-fi',
    sku: 'AUR-SP-04',
    category: 'Âm thanh & Loa',
    price: 9200000,
    rating: 4.9,
    reviewsCount: 78,
    stock: 19,
    description: 'Hệ thống âm thanh đa hướng 360 độ với 6 củ loa neodymium và subwoofer hướng sàn, tái tạo trường âm rộng mở, giàu nhạc tính và độ chi tiết ấn tượng ở mọi góc phòng.',
    specs: {
      'Công suất': '120W RMS High-Output',
      'Driver': '1x Subwoofer 4.5", 3x Midrange 2", 2x Silk Dome Tweeter',
      'Kết nối': 'AirPlay 2, Spotify Connect, Bluetooth 5.3, Wi-Fi 6',
      'Chất liệu': 'Vải len Kvadrat Đan Mạch & Gỗ Sồi tự nhiên',
    },
    features: [
      'Trường âm 360 độ ngập tràn căn phòng',
      'Vật liệu len dệt cao cấp bền đẹp theo năm tháng',
      'Hỗ trợ kết nối âm thanh đa phòng Multi-room không độ trễ',
    ],
    images: ['speaker-1', 'speaker-2'],
    illustrationType: 'speaker',
    badge: 'Premium Edition',
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    variants: {
      colors: ['Gỗ Sồi Tự Nhiên & Len Xám', 'Gỗ Óc Chó & Len Đen'],
    },
    createdAt: '2026-08-28T09:00:00Z',
    isActive: true,
  },
  {
    id: 'prod-05',
    name: 'Bàn phím cơ không dây AURA Precision 75 Gasket',
    slug: 'ban-phim-co-aura-precision-75',
    sku: 'AUR-KB-05',
    category: 'Bàn làm việc & Ánh sáng',
    price: 3490000,
    originalPrice: 3990000,
    discount: 12,
    rating: 4.8,
    reviewsCount: 165,
    stock: 35,
    description: 'Thiết kế CNC nhôm nguyên khối, cấu trúc Gasket-mount 5 lớp tiêu âm đem lại cảm giác gõ thock êm ái, switch bôi trơn sẵn từ nhà máy và kết nối 3 chế độ siêu nhạy.',
    specs: {
      'Layout': '75% nhỏ gọn (82 phím)',
      'Switch': 'AURA Crystal Linear Pre-lubed (45g)',
      'Cấu trúc': 'Full CNC Nhôm, Gasket Mount 5 lớp Poron',
      'Keycap': 'PBT Double-shot Cherry Profile',
      'Pin': '8000mAh (dùng tới 200 giờ)',
    },
    features: [
      'Vỏ nhôm CNC phay tinh xảo với trọng lượng đầm tay 1.8kg',
      'Âm thanh gõ trầm ấm mượt mà không cần mod thêm',
      'Núm xoay kim loại đa chức năng điều khiển âm lượng',
      'Hotswap 5 pin thay switch nhanh chóng',
    ],
    images: ['keyboard-1', 'keyboard-2'],
    illustrationType: 'keyboard',
    badge: 'Hot Deal',
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    variants: {
      colors: ['Xám Bão Stormy', 'Đen Huyền Bí Anodized', 'Trắng Băng Ice White'],
    },
    createdAt: '2026-08-01T11:20:00Z',
    isActive: true,
  },
  {
    id: 'prod-06',
    name: 'Trạm kết nối Thunderbolt 4 AURA Pro Hub 12-in-1',
    slug: 'tram-ket-noi-aura-pro-hub-12-in-1',
    sku: 'AUR-HB-06',
    category: 'Phụ kiện cao cấp',
    price: 4290000,
    rating: 4.7,
    reviewsCount: 54,
    stock: 22,
    description: 'Giải pháp mở rộng kết nối toàn diện cho các nhà sáng tạo nội dung và lập trình viên. Hỗ trợ xuất 2 màn hình 4K@120Hz hoặc 1 màn hình 8K, sạc PD 100W và tản nhiệt buồng hơi thụ động siêu êm.',
    specs: {
      'Băng thông': 'Thunderbolt 4 / USB4 lên tới 40Gbps',
      'Cổng xuất hình': '2x HDMI 2.1, 1x DisplayPort 1.4',
      'Sạc': 'Power Delivery 100W cho Laptop',
      'Mạng': 'Ethernet 2.5 Gigabit siêu tốc',
    },
    features: [
      'Băng thông truyền tải dữ liệu 40Gbps cực đại',
      'Hỗ trợ 2 màn hình ngoài độ phân giải cao sắc nét',
      'Vỏ nhôm tản nhiệt nguyên khối không quạt ồn',
    ],
    images: ['hub-1', 'hub-2'],
    illustrationType: 'hub',
    badge: 'Chuyên nghiệp',
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    variants: {
      colors: ['Xám Không Gian Space Gray', 'Bạc Nguyên Bản'],
    },
    createdAt: '2026-09-10T16:00:00Z',
    isActive: true,
  },
  {
    id: 'prod-07',
    name: 'Bàn nâng hạ thông minh AURA Minimalist Walnut',
    slug: 'ban-nang-ha-aura-minimalist-walnut',
    sku: 'AUR-DK-07',
    category: 'Bàn làm việc & Ánh sáng',
    price: 16800000,
    originalPrice: 18500000,
    discount: 9,
    rating: 5.0,
    reviewsCount: 39,
    stock: 8,
    description: 'Mặt bàn bằng gỗ óc chó Bắc Mỹ nguyên tấm tuyển chọn, kết hợp khung nâng hạ động cơ kép Đức tải trọng 140kg, bảng điều khiển OLED ghi nhớ 4 nấc chiều cao và cảm biến chống va chạm thông minh.',
    specs: {
      'Kích thước': '160cm x 75cm x 3.2cm',
      'Chất liệu mặt': 'Gỗ Óc Chó FAS tuyển chọn phủ dầu lau sinh học',
      'Chiều cao': '62cm - 128cm mượt mà',
      'Động cơ': 'Dual Motor Bosch Technology, 38mm/s, <40dB',
      'Tải trọng': '140kg nâng hạ êm ái',
    },
    features: [
      'Gỗ tự nhiên nguyên tấm với vân gỗ độc bản cho từng sản phẩm',
      'Động cơ kép siêu tĩnh âm với cảm biến chống kẹt thế hệ mới',
      'Bộ quản lý dây điện tích hợp gọn gàng bên dưới mặt bàn',
    ],
    images: ['desk-1', 'desk-2'],
    illustrationType: 'desk',
    badge: 'Cao cấp nhất',
    isFeatured: true,
    isBestSeller: false,
    isNew: false,
    variants: {
      capacities: ['140 x 70 cm', '160 x 75 cm', '180 x 80 cm'],
    },
    createdAt: '2026-07-10T09:00:00Z',
    isActive: true,
  },
  {
    id: 'prod-08',
    name: 'Camera an ninh thông minh AURA Vision 4K AI HDR',
    slug: 'camera-an-ninh-aura-vision-4k',
    sku: 'AUR-CM-08',
    category: 'Gia dụng thông minh',
    price: 2890000,
    rating: 4.8,
    reviewsCount: 112,
    stock: 40,
    description: 'Cảm biến Sony Starvis 2 ghi hình 4K HDR siêu nét kể cả trong bóng tối tuyệt đối. Trí tuệ nhân tạo nhận diện người, thú cưng và gói hàng cục bộ trên thiết bị, bảo mật dữ liệu cấp ngân hàng.',
    specs: {
      'Độ phân giải': '4K UHD (3840 x 2160) @ 30fps',
      'Cảm biến': 'Sony Starvis 2 1/1.8" Color Night Vision',
      'Góc nhìn': '145° siêu rộng chống biến dạng',
      'Lưu trữ': 'MicroSD 512GB / NAS RTSP / Cloud mã hóa E2E',
      'Chống nước': 'IP67 chịu nắng mưa tuyệt đối',
    },
    features: [
      'Nhìn đêm có màu sắc nét với đèn trợ sáng thông minh',
      'AI nhận diện đối tượng không phụ thuộc đám mây',
      'Đàm thoại 2 chiều lọc tiếng ồn gió hiệu quả',
    ],
    images: ['camera-1', 'camera-2'],
    illustrationType: 'camera',
    badge: 'An tâm gia đình',
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    variants: {
      colors: ['Trắng Tuyết Arctic', 'Đen Mờ Than Chì'],
    },
    createdAt: '2026-08-12T13:40:00Z',
    isActive: true,
  },
  {
    id: 'prod-09',
    name: 'Tai nghe TWS AURA Air Pure Hi-Res',
    slug: 'tai-nghe-tws-aura-air-pure',
    sku: 'AUR-HP-09',
    category: 'Âm thanh & Loa',
    price: 3790000,
    originalPrice: 4200000,
    discount: 10,
    rating: 4.8,
    reviewsCount: 88,
    stock: 32,
    description: 'Tai nghe in-ear không dây nhẹ như không với housing gốm zirconia bóng bẩy, driver đồng trục kép và khả năng đàm thoại trong trẻo với thuật toán Bone Conduction dẫn truyền qua xương.',
    specs: {
      'Driver': 'Đồng trục kép 11mm Bass + 6mm Planar Tweeter',
      'Trọng lượng': '4.3g mỗi bên tai',
      'Pin': '36 giờ kèm hộp sạc không dây Qi',
      'Codec': 'LDAC, LHDC 5.0, AAC',
    },
    features: [
      'Housing gốm siêu mịn thân thiện với da tai',
      'Đàm thoại rõ ràng ngay cả khi chạy xe máy tốc độ cao',
      'Kháng nước IP54 cho tập luyện thể thao',
    ],
    images: ['audio-4'],
    illustrationType: 'audio',
    badge: 'Thanh lịch',
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    variants: {
      colors: ['Trắng Gốm Ceramic', 'Đen Bóng Phantom'],
    },
    createdAt: '2026-09-15T15:00:00Z',
    isActive: true,
  },
  {
    id: 'prod-10',
    name: 'Củ sạc siêu nhanh GaN 140W AURA HyperPower',
    slug: 'cu-sac-gan-140w-aura-hyperpower',
    sku: 'AUR-AC-10',
    category: 'Phụ kiện cao cấp',
    price: 1590000,
    originalPrice: 1850000,
    discount: 14,
    rating: 4.9,
    reviewsCount: 204,
    stock: 65,
    description: 'Sử dụng bán dẫn Gallium Nitride thế hệ 4 giúp thu nhỏ kích thước 45% so với củ sạc tiêu chuẩn. 3 cổng Type-C và 1 cổng USB-A cung cấp năng lượng đầy đủ cho MacBook Pro 16", iPad và iPhone cùng lúc.',
    specs: {
      'Công suất tối đa': '140W PD 3.1 (28V/5A)',
      'Số cổng': '3x USB-C + 1x USB-A QC 4.0',
      'Kích thước': '78 x 78 x 32mm',
      'Bảo vệ': 'Kiểm soát nhiệt độ thông minh 3 triệu lần/ngày',
    },
    features: [
      'Sạc đầy 50% pin MacBook Pro 16" chỉ trong 30 phút',
      'Tương thích hoàn hảo với mọi thiết bị hiện đại',
      'Chân cắm gấp gọn tiện lợi khi du lịch',
    ],
    images: ['hub-3'],
    illustrationType: 'hub',
    badge: 'Tiện ích hàng đầu',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    variants: {
      colors: ['Xám Mờ Titan', 'Trắng Băng Giá'],
    },
    createdAt: '2026-08-05T08:00:00Z',
    isActive: true,
  },
];

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    code: 'AURAXIN',
    title: 'Giảm 10% cho thành viên mới',
    discountPercent: 10,
    maxDiscount: 500000,
    minOrder: 1000000,
    validUntil: '2026-12-31',
    usageCount: 142,
    maxUsage: 1000,
    isActive: true,
  },
  {
    code: 'FREESHIP',
    title: 'Miễn phí vận chuyển toàn quốc',
    discountPercent: 0,
    maxDiscount: 40000,
    minOrder: 500000,
    validUntil: '2026-12-31',
    usageCount: 388,
    maxUsage: 2000,
    isActive: true,
  },
  {
    code: 'VIPTECH',
    title: 'Ưu đãi VIP giảm 15% cho đơn lớn',
    discountPercent: 15,
    maxDiscount: 1500000,
    minOrder: 8000000,
    validUntil: '2026-11-30',
    usageCount: 45,
    maxUsage: 200,
    isActive: true,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'AUR-9821',
    customer: {
      name: 'Trần Minh Quân',
      phone: '0903124567',
      email: 'quan.tran@example.com',
      city: 'Hồ Chí Minh',
      district: 'Quận 1',
      ward: 'Phường Bến Nghé',
      address: '42 Nguyễn Huệ, Căn hộ 12B',
      note: 'Giao giờ hành chính, gọi trước 15 phút',
    },
    items: [
      {
        productId: 'prod-01',
        product: INITIAL_PRODUCTS[0],
        quantity: 1,
        selectedColor: 'Đen Titan Obsidian',
      },
      {
        productId: 'prod-10',
        product: INITIAL_PRODUCTS[9],
        quantity: 1,
        selectedColor: 'Xám Mờ Titan',
      },
    ],
    subtotal: 9480000,
    shippingFee: 0,
    discountAmount: 500000,
    couponCode: 'AURAXIN',
    totalAmount: 8980000,
    paymentMethod: 'bank_transfer',
    paymentStatus: 'paid',
    status: 'delivered',
    userId: 'user-02',
    createdAt: '2026-09-20T14:20:00Z',
    updatedAt: '2026-09-23T10:15:00Z',
  },
  {
    id: 'ord-1002',
    orderNumber: 'AUR-9822',
    customer: {
      name: 'Nguyễn Thị Hải Yến',
      phone: '0912384756',
      email: 'haiyen.nguyen@gmail.com',
      city: 'Hà Nội',
      district: 'Quận Ba Đình',
      ward: 'Phường Kim Mã',
      address: '88 Kim Mã, Tòa nhà Văn phòng Tech',
    },
    items: [
      {
        productId: 'prod-03',
        product: INITIAL_PRODUCTS[2],
        quantity: 2,
        selectedColor: 'Đen Mờ Matte Black',
      },
    ],
    subtotal: 5300000,
    shippingFee: 30000,
    discountAmount: 0,
    totalAmount: 5330000,
    paymentMethod: 'cod',
    paymentStatus: 'pending',
    status: 'shipping',
    userId: 'user-03',
    createdAt: '2026-09-25T09:12:00Z',
    updatedAt: '2026-09-26T08:30:00Z',
  },
  {
    id: 'ord-1003',
    orderNumber: 'AUR-9823',
    customer: {
      name: 'Lê Hoàng Nam',
      phone: '0988776655',
      email: 'tyce@example.com',
      city: 'Đà Nẵng',
      district: 'Quận Hải Châu',
      ward: 'Phường Thạch Thang',
      address: '15 Trần Phú',
    },
    items: [
      {
        productId: 'prod-02',
        product: INITIAL_PRODUCTS[1],
        quantity: 1,
        selectedColor: 'Titanium Tự Nhiên',
      },
    ],
    subtotal: 11490000,
    shippingFee: 0,
    discountAmount: 1500000,
    couponCode: 'VIPTECH',
    totalAmount: 9990000,
    paymentMethod: 'bank_transfer',
    paymentStatus: 'paid',
    status: 'processing',
    userId: 'user-current',
    createdAt: '2026-09-27T16:45:00Z',
    updatedAt: '2026-09-27T17:00:00Z',
  },
  {
    id: 'ord-1004',
    orderNumber: 'AUR-9824',
    customer: {
      name: 'Đặng Tuấn Anh',
      phone: '0933221100',
      email: 'tuananh.dang@fintech.vn',
      city: 'Hồ Chí Minh',
      district: 'Quận 7',
      ward: 'Phường Tân Phong',
      address: 'Khu biệt thự Phú Mỹ Hưng',
    },
    items: [
      {
        productId: 'prod-07',
        product: INITIAL_PRODUCTS[6],
        quantity: 1,
        selectedCapacity: '160 x 75 cm',
      },
    ],
    subtotal: 16800000,
    shippingFee: 0,
    discountAmount: 0,
    totalAmount: 16800000,
    paymentMethod: 'credit_card',
    paymentStatus: 'paid',
    status: 'confirmed',
    userId: 'user-04',
    createdAt: '2026-09-28T11:05:00Z',
    updatedAt: '2026-09-28T11:30:00Z',
  },
  {
    id: 'ord-1005',
    orderNumber: 'AUR-9825',
    customer: {
      name: 'Phạm Thanh Thảo',
      phone: '0977889900',
      email: 'thanhthao.pham@studio.design',
      city: 'Hồ Chí Minh',
      district: 'Quận Bình Thạnh',
      ward: 'Phường 22',
      address: '208 Nguyễn Hữu Cảnh, Tòa Landmark 81',
    },
    items: [
      {
        productId: 'prod-05',
        product: INITIAL_PRODUCTS[4],
        quantity: 1,
        selectedColor: 'Xám Bão Stormy',
      },
    ],
    subtotal: 3490000,
    shippingFee: 30000,
    discountAmount: 349000,
    couponCode: 'AURAXIN',
    totalAmount: 3171000,
    paymentMethod: 'cod',
    paymentStatus: 'pending',
    status: 'pending',
    createdAt: '2026-09-28T15:10:00Z',
    updatedAt: '2026-09-28T15:10:00Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin',
    name: 'Quản Trị Viên AURA',
    email: 'admin@aura.vn',
    phone: '0909000999',
    address: 'Toà nhà AURA Innovation, 86 Nguyễn Trãi',
    city: 'Hồ Chí Minh',
    district: 'Quận 1',
    role: 'admin',
    createdAt: '2026-01-01T00:00:00Z',
    totalSpent: 0,
    ordersCount: 0,
    isLocked: false,
  },
  {
    id: 'user-current',
    name: 'Lê Hoàng Nam',
    email: 'tyce@example.com',
    phone: '0988776655',
    address: '15 Trần Phú',
    city: 'Đà Nẵng',
    district: 'Quận Hải Châu',
    role: 'customer',
    createdAt: '2026-03-12T10:00:00Z',
    totalSpent: 9990000,
    ordersCount: 1,
    isLocked: false,
  },
  {
    id: 'user-02',
    name: 'Trần Minh Quân',
    email: 'quan.tran@example.com',
    phone: '0903124567',
    address: '42 Nguyễn Huệ, Căn hộ 12B',
    city: 'Hồ Chí Minh',
    district: 'Quận 1',
    role: 'customer',
    createdAt: '2026-04-18T14:30:00Z',
    totalSpent: 8980000,
    ordersCount: 1,
    isLocked: false,
  },
  {
    id: 'user-03',
    name: 'Nguyễn Thị Hải Yến',
    email: 'haiyen.nguyen@gmail.com',
    phone: '0912384756',
    address: '88 Kim Mã',
    city: 'Hà Nội',
    district: 'Quận Ba Đình',
    role: 'customer',
    createdAt: '2026-05-22T08:15:00Z',
    totalSpent: 5330000,
    ordersCount: 1,
    isLocked: false,
  },
  {
    id: 'user-04',
    name: 'Đặng Tuấn Anh',
    email: 'tuananh.dang@fintech.vn',
    phone: '0933221100',
    address: 'Khu biệt thự Phú Mỹ Hưng',
    city: 'Hồ Chí Minh',
    district: 'Quận 7',
    role: 'customer',
    createdAt: '2026-06-05T16:20:00Z',
    totalSpent: 16800000,
    ordersCount: 1,
    isLocked: false,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-01',
    productId: 'prod-01',
    userName: 'Vũ Đức Thịnh (Kỹ sư âm thanh)',
    rating: 5,
    comment: 'Khả năng cách âm chủ động thực sự bất ngờ, ngang tầm các dòng flagship cao cấp nhất hiện tại. Dải trầm xuống sâu gọn gàng, không bị lùng bùng. Thiết kế gọng nhôm rất đầm và êm tai.',
    date: '2026-09-18',
    verifiedPurchase: true,
  },
  {
    id: 'rev-02',
    productId: 'prod-01',
    userName: 'Mai Lan Phương',
    rating: 5,
    comment: 'Màu Titan cực kỳ sang chảnh! Mình đeo đi làm cả ngày ở quán cà phê ồn ào bật ANC lên là như bước vào một thế giới yên tĩnh riêng. Đáng từng đồng bỏ ra.',
    date: '2026-09-22',
    verifiedPurchase: true,
  },
  {
    id: 'rev-03',
    productId: 'prod-02',
    userName: 'Hoàng Bách (Vận động viên Marathon)',
    rating: 5,
    comment: 'Chất liệu Titanium siêu nhẹ khi chạy dài không có cảm giác vướng víu. GPS bắt sóng rất nhanh kể cả trong phố nhiều nhà cao tầng. Pin chạy cả tuần mới cần sạc.',
    date: '2026-09-15',
    verifiedPurchase: true,
  },
  {
    id: 'rev-04',
    productId: 'prod-03',
    userName: 'Nguyễn Kiến Trúc (Architect)',
    rating: 5,
    comment: 'Đèn có độ hoàn màu Ra98 chuẩn xác, rất thích hợp khi mình vẽ bản thảo và chọn màu mẫu vật liệu ban đêm. Khớp gập cơ khí êm ru.',
    date: '2026-09-24',
    verifiedPurchase: true,
  },
  {
    id: 'rev-05',
    productId: 'prod-01',
    userName: 'Trần Minh Quân',
    rating: 4,
    comment: 'Chất âm và chống ồn rất tốt. Trừ một sao vì hộp đựng hơi to, mang đi công tác chiếm nhiều chỗ trong balo.',
    date: '2026-09-24',
    verifiedPurchase: true,
    userId: 'user-02',
  },
  {
    id: 'rev-06',
    productId: 'prod-02',
    userName: 'Lý Gia Hân',
    rating: 4,
    comment: 'Màn hình sáng rõ ngoài trời, dây đeo êm. Ứng dụng đồng bộ đôi lúc chậm vài giây nhưng không ảnh hưởng nhiều.',
    date: '2026-09-20',
    verifiedPurchase: false,
  },
  {
    id: 'rev-07',
    productId: 'prod-03',
    userName: 'Nguyễn Thị Hải Yến',
    rating: 5,
    comment: 'Mua hai chiếc cho văn phòng. Ánh sáng dịu, làm việc buổi tối đỡ mỏi mắt hẳn. Cổng sạc ở chân đế rất tiện.',
    date: '2026-09-27',
    verifiedPurchase: false,
    userId: 'user-03',
  },
  {
    id: 'rev-08',
    productId: 'prod-04',
    userName: 'Phan Quốc Bảo',
    rating: 5,
    comment: 'Đặt giữa phòng khách nghe ở góc nào cũng đều tiếng. Vỏ len và gỗ sồi hoàn thiện rất kỹ, hợp nội thất.',
    date: '2026-09-12',
    verifiedPurchase: false,
  },
  {
    id: 'rev-09',
    productId: 'prod-04',
    userName: 'Đỗ Thu Trang',
    rating: 4,
    comment: 'Âm trầm chắc, kết nối AirPlay ổn định. Giá hơi cao nhưng xứng đáng với chất lượng hoàn thiện.',
    date: '2026-09-19',
    verifiedPurchase: false,
  },
  {
    id: 'rev-10',
    productId: 'prod-05',
    userName: 'Bùi Anh Khoa (Lập trình viên)',
    rating: 5,
    comment: 'Gõ rất êm và đầm tay, không cần mod thêm. Pin dùng hơn hai tuần mới phải sạc với đèn nền tắt.',
    date: '2026-09-10',
    verifiedPurchase: false,
  },
  {
    id: 'rev-11',
    productId: 'prod-05',
    userName: 'Võ Ngọc Mai',
    rating: 4,
    comment: 'Thiết kế đẹp, keycap PBT sờ thích. Bàn phím khá nặng nên ít khi mang theo ra ngoài.',
    date: '2026-09-21',
    verifiedPurchase: false,
  },
  {
    id: 'rev-12',
    productId: 'prod-06',
    userName: 'Hồ Thanh Tùng',
    rating: 5,
    comment: 'Xuất hai màn hình 4K ổn định, sạc laptop đủ công suất. Vỏ nhôm ấm lên khi tải nặng nhưng không quá nóng.',
    date: '2026-09-16',
    verifiedPurchase: false,
  },
  {
    id: 'rev-13',
    productId: 'prod-07',
    userName: 'Đặng Tuấn Anh',
    rating: 5,
    comment: 'Mặt gỗ óc chó vân rất đẹp, nâng hạ êm gần như không nghe tiếng. Đội lắp đặt làm việc cẩn thận.',
    date: '2026-09-29',
    verifiedPurchase: false,
    userId: 'user-04',
  },
  {
    id: 'rev-14',
    productId: 'prod-08',
    userName: 'Lâm Hoài Nam',
    rating: 5,
    comment: 'Hình ảnh ban đêm có màu rõ nét, nhận diện người khá chính xác, ít báo động giả do thú cưng.',
    date: '2026-09-08',
    verifiedPurchase: false,
  },
  {
    id: 'rev-15',
    productId: 'prod-08',
    userName: 'Trịnh Bảo Ngọc',
    rating: 4,
    comment: 'Lắp đặt dễ, ứng dụng trực quan. Mong hãng bổ sung thêm gói lưu trữ đám mây dài ngày hơn.',
    date: '2026-09-23',
    verifiedPurchase: false,
  },
  {
    id: 'rev-16',
    productId: 'prod-09',
    userName: 'Cao Minh Đức',
    rating: 5,
    comment: 'Đeo nhẹ và chắc tai, chạy bộ không rơi. Đàm thoại ngoài đường người nghe vẫn rõ tiếng.',
    date: '2026-09-25',
    verifiedPurchase: false,
  },
  {
    id: 'rev-17',
    productId: 'prod-10',
    userName: 'Trần Minh Quân',
    rating: 5,
    comment: 'Sạc cùng lúc laptop và điện thoại vẫn đủ công suất. Kích thước nhỏ gọn, chân cắm gập tiện mang đi.',
    date: '2026-09-24',
    verifiedPurchase: true,
    userId: 'user-02',
  },
  {
    id: 'rev-18',
    productId: 'prod-10',
    userName: 'Ngô Phương Linh',
    rating: 4,
    comment: 'Sạc nhanh, ít nóng. Dây sạc không kèm theo nên cần mua thêm cáp 140W.',
    date: '2026-09-17',
    verifiedPurchase: false,
  },
];

/**
 * Default passwords of the seeded accounts. They are hashed on first run and only
 * exist so the sample data can be signed in to — change them before going live.
 */
export const SEED_PASSWORDS: Record<string, string> = {
  'user-admin': 'admin123',
  'user-current': '123456',
  'user-02': '123456',
  'user-03': '123456',
  'user-04': '123456',
  'user-05': '123456',
  'user-06': '123456',
  'user-07': '123456',
  'user-08': '123456',
  'user-09': '123456',
  'user-10': '123456',
  'user-11': '123456',
  'user-12': '123456',
};
