import { IllustrationType } from '../../shared/types';

/**
 * The sample catalogue beyond the first ten products. It is spread on purpose over
 * every price range and every rating level, so that filtering and sorting have
 * something to show.
 *
 * `ratings` lists the stars of the product's sample reviews; the review texts and the
 * orders behind them are produced by seedBuilder.ts.
 */

/** What kind of thing the product is, which decides what a reviewer would praise or fault */
export type ProductKind = 'audio' | 'wearable' | 'desk' | 'accessory' | 'home';

export type CatalogProduct = {
  id: string;
  name: string;
  slug: string;
  sku: string;
  category: string;
  price: number;
  originalPrice?: number;
  stock: number;
  kind: ProductKind;
  /** How a reviewer would call it: "tai nghe", "đồng hồ"… */
  noun: string;
  illustrationType: IllustrationType;
  badge?: string;
  isFeatured?: boolean;
  isBestSeller?: boolean;
  isNew?: boolean;
  colors?: string[];
  capacities?: string[];
  createdAt: string;
  description: string;
  features: string[];
  specs: Record<string, string>;
  ratings: number[];
};

const AUDIO = 'Âm thanh & Loa';
const WATCH = 'Đồng hồ & Vòng đeo';
const DESK = 'Bàn làm việc & Ánh sáng';
const ACCESSORY = 'Phụ kiện cao cấp';
const HOME = 'Gia dụng thông minh';

export const EXTRA_PRODUCTS: CatalogProduct[] = [
  // ------------------------------------------------------------- Âm thanh & Loa
  {
    id: 'prod-11',
    name: 'Tai nghe chụp tai AURA Studio Lite',
    slug: 'tai-nghe-chup-tai-aura-studio-lite',
    sku: 'AUR-HP-11',
    category: AUDIO,
    price: 2490000,
    originalPrice: 2990000,
    stock: 46,
    kind: 'audio',
    noun: 'tai nghe',
    illustrationType: 'audio',
    isBestSeller: true,
    colors: ['Đen Nhám', 'Trắng Ngà', 'Xanh Navy'],
    createdAt: '2026-05-12T09:00:00Z',
    description:
      'Phiên bản gọn nhẹ của dòng Studio: chống ồn chủ động 30dB, pin 35 giờ và đệm tai êm cho cả ngày làm việc, với mức giá dễ tiếp cận hơn.',
    features: [
      'Chống ồn chủ động 30dB với hai chế độ xuyên âm',
      'Pin 35 giờ, sạc 10 phút nghe 4 giờ',
      'Kết nối cùng lúc hai thiết bị',
      'Gập gọn, kèm túi vải đựng',
    ],
    specs: {
      Driver: '40mm Dynamic',
      'Chống ồn': 'ANC 30dB',
      Pin: '35 giờ',
      'Kết nối': 'Bluetooth 5.3, AAC, jack 3.5mm',
      'Trọng lượng': '215g',
    },
    ratings: [5, 5, 4, 4, 4, 5, 3],
  },
  {
    id: 'prod-12',
    name: 'Tai nghe thể thao AURA Sport Fit',
    slug: 'tai-nghe-the-thao-aura-sport-fit',
    sku: 'AUR-HP-12',
    category: AUDIO,
    price: 1290000,
    stock: 80,
    kind: 'audio',
    noun: 'tai nghe',
    illustrationType: 'audio',
    colors: ['Đen', 'Xanh Dương'],
    createdAt: '2026-06-03T09:00:00Z',
    description:
      'Tai nghe đeo cổ dành cho chạy bộ và tập luyện: bám chắc, kháng mồ hôi IPX5 và pin 15 giờ cho cả tuần tập.',
    features: [
      'Thiết kế đeo cổ, không rơi khi vận động mạnh',
      'Kháng nước và mồ hôi IPX5',
      'Pin 15 giờ nghe nhạc liên tục',
      'Củ tai nam châm, tự ngắt nhạc khi hít vào nhau',
    ],
    specs: {
      Driver: '12mm Dynamic',
      'Kháng nước': 'IPX5',
      Pin: '15 giờ',
      'Kết nối': 'Bluetooth 5.2, AAC',
      'Trọng lượng': '21g',
    },
    ratings: [4, 4, 5, 3, 4, 3],
  },
  {
    id: 'prod-13',
    name: 'Loa bluetooth mini AURA Pebble',
    slug: 'loa-bluetooth-mini-aura-pebble',
    sku: 'AUR-SP-13',
    category: AUDIO,
    price: 890000,
    originalPrice: 1090000,
    stock: 120,
    kind: 'audio',
    noun: 'loa',
    illustrationType: 'speaker',
    badge: 'Giá tốt',
    isBestSeller: true,
    colors: ['Xám Đá', 'Cam San Hô', 'Xanh Rêu'],
    createdAt: '2026-04-20T09:00:00Z',
    description:
      'Chiếc loa nằm gọn trong lòng bàn tay với âm lượng đủ cho một căn phòng, móc treo tiện lợi và pin 12 giờ.',
    features: [
      'Nhỏ gọn 280g, có dây treo balo',
      'Kháng nước IP67, dùng được ngoài trời',
      'Pin 12 giờ',
      'Ghép đôi hai loa thành âm thanh stereo',
    ],
    specs: {
      'Công suất': '8W',
      'Kháng nước': 'IP67',
      Pin: '12 giờ',
      'Kết nối': 'Bluetooth 5.3',
      'Trọng lượng': '280g',
    },
    ratings: [5, 4, 4, 5, 4, 4, 5, 3],
  },
  {
    id: 'prod-14',
    name: 'Loa di động chống nước AURA Roam',
    slug: 'loa-di-dong-chong-nuoc-aura-roam',
    sku: 'AUR-SP-14',
    category: AUDIO,
    price: 2190000,
    stock: 38,
    kind: 'audio',
    noun: 'loa',
    illustrationType: 'speaker',
    colors: ['Đen', 'Xanh Dương', 'Đỏ'],
    createdAt: '2026-06-18T09:00:00Z',
    description:
      'Loa hình trụ cho những chuyến đi: âm trầm chắc nhờ hai màng cộng hưởng, chịu nước IP67 và pin 20 giờ.',
    features: [
      'Hai màng cộng hưởng thụ động cho âm trầm sâu',
      'Chống nước và bụi IP67',
      'Pin 20 giờ, kiêm sạc dự phòng cho điện thoại',
      'Kết nối chuỗi nhiều loa cùng lúc',
    ],
    specs: {
      'Công suất': '30W',
      'Kháng nước': 'IP67',
      Pin: '20 giờ',
      'Kết nối': 'Bluetooth 5.3, AUX',
      'Trọng lượng': '960g',
    },
    ratings: [5, 5, 4, 5, 4],
  },
  {
    id: 'prod-15',
    name: 'Loa thanh AURA Cinema Bar 5.1',
    slug: 'loa-thanh-aura-cinema-bar-5-1',
    sku: 'AUR-SP-15',
    category: AUDIO,
    price: 12900000,
    originalPrice: 14900000,
    stock: 12,
    kind: 'audio',
    noun: 'loa thanh',
    illustrationType: 'speaker',
    badge: 'Rạp tại gia',
    isFeatured: true,
    createdAt: '2026-07-08T09:00:00Z',
    description:
      'Hệ thống loa thanh kèm loa siêu trầm không dây, hỗ trợ Dolby Atmos, đem trải nghiệm rạp chiếu phim về phòng khách.',
    features: [
      'Âm thanh vòm 5.1 với Dolby Atmos',
      'Loa siêu trầm không dây 8 inch',
      'HDMI eARC, truyền tín hiệu 4K HDR',
      'Tự cân chỉnh âm thanh theo phòng',
    ],
    specs: {
      'Công suất': '520W',
      'Số kênh': '5.1',
      'Kết nối': 'HDMI eARC, Optical, Bluetooth 5.3, Wi-Fi',
      'Định dạng': 'Dolby Atmos, DTS:X',
      'Chiều dài': '105cm',
    },
    ratings: [5, 5, 5, 4, 5],
  },
  {
    id: 'prod-16',
    name: 'Micro thu âm AURA Voice USB',
    slug: 'micro-thu-am-aura-voice-usb',
    sku: 'AUR-MC-16',
    category: AUDIO,
    price: 2790000,
    stock: 27,
    kind: 'audio',
    noun: 'micro',
    illustrationType: 'audio',
    isNew: true,
    colors: ['Đen', 'Bạc'],
    createdAt: '2026-08-22T09:00:00Z',
    description:
      'Micro condenser cắm là dùng cho podcast, họp trực tuyến và thu âm tại nhà, với bốn hướng thu và nút tắt tiếng cảm ứng.',
    features: [
      'Bốn hướng thu: một hướng, hai hướng, đa hướng, stereo',
      'Cắm USB-C là dùng, không cần sound card',
      'Nút tắt tiếng cảm ứng có đèn báo',
      'Kèm chân đế kim loại và màng lọc',
    ],
    specs: {
      'Loại micro': 'Condenser, 3 màng thu',
      'Độ phân giải': '24bit / 96kHz',
      'Kết nối': 'USB-C, jack tai nghe 3.5mm',
      'Tần số': '20Hz – 20kHz',
      'Trọng lượng': '560g',
    },
    ratings: [4, 5, 4, 4],
  },
  {
    id: 'prod-17',
    name: 'Tai nghe gaming AURA Arena 7.1',
    slug: 'tai-nghe-gaming-aura-arena-7-1',
    sku: 'AUR-HP-17',
    category: AUDIO,
    price: 3290000,
    originalPrice: 3690000,
    stock: 8,
    kind: 'audio',
    noun: 'tai nghe',
    illustrationType: 'audio',
    colors: ['Đen', 'Trắng'],
    createdAt: '2026-05-30T09:00:00Z',
    description:
      'Tai nghe chơi game không dây độ trễ thấp, âm thanh vòm 7.1 giả lập và micro tháo rời lọc tiếng ồn.',
    features: [
      'Kết nối 2.4GHz độ trễ thấp và Bluetooth',
      'Âm thanh vòm 7.1 giả lập',
      'Micro tháo rời, lọc tiếng ồn',
      'Pin 40 giờ',
    ],
    specs: {
      Driver: '50mm Neodymium',
      'Kết nối': '2.4GHz, Bluetooth 5.2, USB-C',
      Pin: '40 giờ',
      Micro: 'Tháo rời, đa hướng',
      'Trọng lượng': '310g',
    },
    ratings: [4, 3, 4, 5, 3, 4, 2],
  },
  {
    id: 'prod-18',
    name: 'Mâm đĩa than AURA Vinyl Classic',
    slug: 'mam-dia-than-aura-vinyl-classic',
    sku: 'AUR-TT-18',
    category: AUDIO,
    price: 14500000,
    stock: 5,
    kind: 'audio',
    noun: 'mâm đĩa',
    illustrationType: 'speaker',
    badge: 'Cho người sành nhạc',
    capacities: ['Gỗ Óc Chó', 'Đen Piano'],
    createdAt: '2026-03-15T09:00:00Z',
    description:
      'Mâm đĩa than truyền động dây cu-roa, đế gỗ nguyên khối và kim MM lắp sẵn, dành cho những buổi tối nghe nhạc chậm rãi.',
    features: [
      'Truyền động dây cu-roa, giảm rung động cơ',
      'Tay cần nhôm cân chỉnh sẵn từ nhà máy',
      'Tích hợp phono preamp, cắm thẳng vào loa',
      'Hai tốc độ 33⅓ và 45 vòng/phút',
    ],
    specs: {
      'Truyền động': 'Dây cu-roa',
      'Tốc độ': '33⅓, 45 vòng/phút',
      'Đầu kim': 'Moving Magnet',
      'Ngõ ra': 'RCA, Bluetooth',
      'Trọng lượng': '5.4kg',
    },
    ratings: [5, 5, 5],
  },

  // --------------------------------------------------------- Đồng hồ & Vòng đeo
  {
    id: 'prod-19',
    name: 'Vòng đeo sức khỏe AURA Band 5',
    slug: 'vong-deo-suc-khoe-aura-band-5',
    sku: 'AUR-WT-19',
    category: WATCH,
    price: 990000,
    originalPrice: 1190000,
    stock: 150,
    kind: 'wearable',
    noun: 'vòng đeo',
    illustrationType: 'watch',
    badge: 'Bán chạy',
    isBestSeller: true,
    colors: ['Đen', 'Hồng Phấn', 'Xanh Bạc Hà'],
    createdAt: '2026-04-05T09:00:00Z',
    description:
      'Vòng đeo theo dõi nhịp tim, giấc ngủ và hơn 100 bài tập, với màn hình AMOLED và pin hai tuần.',
    features: [
      'Theo dõi nhịp tim và SpO2 liên tục',
      'Phân tích giấc ngủ theo từng giai đoạn',
      'Hơn 100 chế độ luyện tập',
      'Pin 14 ngày, chống nước 5ATM',
    ],
    specs: {
      'Màn hình': '1.62 inch AMOLED',
      'Chống nước': '5ATM',
      Pin: '14 ngày',
      'Cảm biến': 'Nhịp tim, SpO2, gia tốc',
      'Trọng lượng': '14g',
    },
    ratings: [5, 4, 4, 5, 4, 3, 4, 5, 4],
  },
  {
    id: 'prod-20',
    name: 'Đồng hồ thông minh AURA Chrono Lite',
    slug: 'dong-ho-thong-minh-aura-chrono-lite',
    sku: 'AUR-WT-20',
    category: WATCH,
    price: 3490000,
    stock: 42,
    kind: 'wearable',
    noun: 'đồng hồ',
    illustrationType: 'watch',
    colors: ['Đen', 'Bạc', 'Vàng Hồng'],
    createdAt: '2026-06-10T09:00:00Z',
    description:
      'Đồng hồ thông minh vỏ nhôm mỏng nhẹ: nghe gọi trên cổ tay, GPS độc lập và pin 7 ngày.',
    features: [
      'Nghe gọi Bluetooth trực tiếp trên đồng hồ',
      'GPS tích hợp, không cần mang điện thoại',
      'Màn hình AMOLED luôn bật',
      'Pin 7 ngày',
    ],
    specs: {
      'Chất liệu vỏ': 'Nhôm',
      'Màn hình': '1.39 inch AMOLED',
      'Chống nước': '5ATM',
      Pin: '7 ngày',
      'Cảm biến': 'Nhịp tim, SpO2, GPS',
    },
    ratings: [4, 4, 5, 4, 3, 4],
  },
  {
    id: 'prod-21',
    name: 'Đồng hồ AURA Chrono Classic dây da',
    slug: 'dong-ho-aura-chrono-classic-day-da',
    sku: 'AUR-WT-21',
    category: WATCH,
    price: 5990000,
    originalPrice: 6790000,
    stock: 18,
    kind: 'wearable',
    noun: 'đồng hồ',
    illustrationType: 'watch',
    colors: ['Dây Nâu – Mặt Trắng', 'Dây Đen – Mặt Đen'],
    createdAt: '2026-02-28T09:00:00Z',
    description:
      'Đồng hồ kim cổ điển với bộ máy thông minh ẩn bên trong: nhận thông báo bằng rung, đếm bước và pin 30 ngày.',
    features: [
      'Mặt kim cổ điển, kính sapphire',
      'Rung báo cuộc gọi và tin nhắn',
      'Dây da Ý thay nhanh không cần dụng cụ',
      'Pin 30 ngày',
    ],
    specs: {
      'Chất liệu vỏ': 'Thép không gỉ 316L',
      'Mặt kính': 'Sapphire',
      'Chống nước': '5ATM',
      Pin: '30 ngày',
      'Đường kính': '40mm',
    },
    ratings: [5, 5, 4, 5],
  },
  {
    id: 'prod-22',
    name: 'Đồng hồ thể thao AURA Trail GPS',
    slug: 'dong-ho-the-thao-aura-trail-gps',
    sku: 'AUR-WT-22',
    category: WATCH,
    price: 7490000,
    stock: 22,
    kind: 'wearable',
    noun: 'đồng hồ',
    illustrationType: 'watch',
    isNew: true,
    colors: ['Đen', 'Cam Dã Ngoại'],
    createdAt: '2026-08-05T09:00:00Z',
    description:
      'Đồng hồ cho người chạy địa hình và leo núi: bản đồ ngoại tuyến, đo độ cao khí áp và pin 40 giờ khi bật GPS.',
    features: [
      'GPS tần số kép với bản đồ ngoại tuyến',
      'Đo độ cao, khí áp và la bàn',
      'Pin 40 giờ bật GPS, 21 ngày dùng thường',
      'Đạt chuẩn độ bền quân đội MIL-STD-810',
    ],
    specs: {
      'Chất liệu vỏ': 'Polymer gia cường sợi, viền thép',
      'Màn hình': '1.3 inch MIP',
      'Chống nước': '10ATM',
      Pin: '21 ngày',
      'Trọng lượng': '52g',
    },
    ratings: [5, 4, 5, 4, 4],
  },
  {
    id: 'prod-23',
    name: 'Nhẫn thông minh AURA Ring',
    slug: 'nhan-thong-minh-aura-ring',
    sku: 'AUR-RG-23',
    category: WATCH,
    price: 6290000,
    stock: 0,
    kind: 'wearable',
    noun: 'nhẫn',
    illustrationType: 'watch',
    badge: 'Sắp có hàng',
    colors: ['Bạc', 'Đen', 'Vàng'],
    capacities: ['Size 8', 'Size 10', 'Size 12'],
    createdAt: '2026-07-20T09:00:00Z',
    description:
      'Chiếc nhẫn Titanium theo dõi giấc ngủ, nhịp tim và thân nhiệt suốt ngày đêm mà không cần màn hình.',
    features: [
      'Theo dõi giấc ngủ, nhịp tim và thân nhiệt',
      'Vỏ Titanium, nặng chưa đến 3g',
      'Pin 6 ngày, kèm hộp sạc',
      'Chống nước 100m',
    ],
    specs: {
      'Chất liệu': 'Titanium',
      'Chống nước': '10ATM',
      Pin: '6 ngày',
      'Cảm biến': 'Nhịp tim, SpO2, thân nhiệt',
      'Trọng lượng': '2.8g',
    },
    ratings: [4, 3, 4, 3],
  },
  {
    id: 'prod-24',
    name: 'Dây đeo thép không gỉ AURA Strap 22mm',
    slug: 'day-deo-thep-khong-gi-aura-strap-22mm',
    sku: 'AUR-ST-24',
    category: WATCH,
    price: 390000,
    stock: 200,
    kind: 'accessory',
    noun: 'dây đeo',
    illustrationType: 'watch',
    capacities: ['Mắt đúc', 'Mắt lưới Milanese', 'Mắt gạch'],
    createdAt: '2026-03-02T09:00:00Z',
    description:
      'Dây đeo thay thế bằng thép không gỉ cỡ 22mm với chốt tháo nhanh, vừa với các dòng AURA Chrono và hầu hết đồng hồ cùng cỡ.',
    features: [
      'Chốt tháo nhanh, thay dây trong vài giây',
      'Tháo bớt mắt dây để vừa cổ tay từ 14 đến 21cm',
      'Khóa gập an toàn',
    ],
    specs: {
      'Bề rộng': '22mm',
      'Chất liệu': 'Thép không gỉ 316L',
      Khóa: 'Khóa gập thép không gỉ',
    },
    ratings: [4, 3, 3, 4, 2, 3],
  },

  // ---------------------------------------------------- Bàn làm việc & Ánh sáng
  {
    id: 'prod-25',
    name: 'Chuột không dây AURA Glide',
    slug: 'chuot-khong-day-aura-glide',
    sku: 'AUR-MS-25',
    category: DESK,
    price: 1190000,
    stock: 95,
    kind: 'desk',
    noun: 'chuột',
    illustrationType: 'keyboard',
    isBestSeller: true,
    colors: ['Xám Than', 'Trắng'],
    createdAt: '2026-04-12T09:00:00Z',
    description:
      'Chuột công thái học bấm êm, cuộn nhanh bằng bánh xe kim loại và dùng được trên cả mặt kính.',
    features: [
      'Nút bấm giảm 90% tiếng ồn',
      'Cảm biến 4000 DPI, dùng được trên mặt kính',
      'Kết nối ba thiết bị, chuyển bằng một nút',
      'Pin 70 ngày, sạc USB-C',
    ],
    specs: {
      'Cảm biến': '4000 DPI',
      'Kết nối': 'Bluetooth 5.1, USB receiver',
      Pin: '70 ngày',
      'Số nút': '6',
      'Trọng lượng': '99g',
    },
    ratings: [5, 5, 4, 4, 5, 4, 5],
  },
  {
    id: 'prod-26',
    name: 'Ghế công thái học AURA ErgoMesh',
    slug: 'ghe-cong-thai-hoc-aura-ergomesh',
    sku: 'AUR-CH-26',
    category: DESK,
    price: 8900000,
    originalPrice: 10500000,
    stock: 14,
    kind: 'desk',
    noun: 'ghế',
    illustrationType: 'desk',
    isFeatured: true,
    colors: ['Đen', 'Xám Sáng'],
    createdAt: '2026-05-25T09:00:00Z',
    description:
      'Ghế lưới nâng đỡ thắt lưng chủ động, tay vịn chỉnh bốn chiều và tựa đầu điều chỉnh được, cho những ngày ngồi tám tiếng.',
    features: [
      'Đỡ thắt lưng tự điều chỉnh theo tư thế',
      'Lưng và đệm lưới thoáng khí',
      'Tay vịn 4D, tựa đầu chỉnh độ cao và góc',
      'Ngả lưng đến 135°, khóa ở bốn nấc',
    ],
    specs: {
      'Chất liệu': 'Lưới đàn hồi, khung nhôm',
      'Tải trọng': '150kg',
      'Chiều cao ghế': '45 – 55cm',
      'Góc ngả': '90° – 135°',
      'Bảo hành': '5 năm khung ghế',
    },
    ratings: [5, 4, 5, 5, 4, 4],
  },
  {
    id: 'prod-27',
    name: 'Đế tản nhiệt laptop AURA Chill',
    slug: 'de-tan-nhiet-laptop-aura-chill',
    sku: 'AUR-LS-27',
    category: DESK,
    price: 690000,
    stock: 140,
    kind: 'desk',
    noun: 'đế tản nhiệt',
    illustrationType: 'desk',
    createdAt: '2026-03-20T09:00:00Z',
    description:
      'Đế tản nhiệt mặt lưới kim loại với quạt lớn chạy êm, nâng laptop nghiêng vừa tầm gõ và giữ máy mát khi làm việc nặng.',
    features: [
      'Quạt lớn chạy êm, lấy điện từ cổng USB của máy',
      'Mặt lưới kim loại thoát nhiệt nhanh',
      'Hai mức nghiêng cho tư thế gõ thoải mái',
      'Chân cao su chống trượt',
    ],
    specs: {
      'Chất liệu': 'Lưới thép, khung nhựa ABS',
      'Tương thích': 'Laptop 12 – 17 inch',
      Quạt: '200mm, 700 vòng/phút',
      'Trọng lượng': '720g',
    },
    ratings: [5, 5, 4, 5, 5],
  },
  {
    id: 'prod-28',
    name: 'Màn hình AURA View 27 inch 4K',
    slug: 'man-hinh-aura-view-27-inch-4k',
    sku: 'AUR-MN-28',
    category: DESK,
    price: 9990000,
    originalPrice: 11490000,
    stock: 20,
    kind: 'desk',
    noun: 'màn hình',
    illustrationType: 'desk',
    badge: 'Cho dân sáng tạo',
    isFeatured: true,
    createdAt: '2026-06-25T09:00:00Z',
    description:
      'Màn hình IPS 4K phủ 98% DCI-P3, cân màu sẵn từ nhà máy và một cổng USB-C vừa truyền hình vừa sạc laptop 90W.',
    features: [
      'Độ phân giải 4K, phủ 98% DCI-P3',
      'Cân màu sẵn, Delta E nhỏ hơn 2',
      'USB-C truyền hình, dữ liệu và sạc 90W',
      'Chân đế xoay dọc, chỉnh cao 13cm',
    ],
    specs: {
      'Kích thước': '27 inch',
      'Độ phân giải': '3840 x 2160',
      'Tấm nền': 'IPS, 60Hz',
      'Độ phủ màu': '98% DCI-P3',
      'Cổng kết nối': 'USB-C 90W, HDMI 2.0, DisplayPort 1.4',
    },
    ratings: [4, 4, 3, 4, 5, 3, 4],
  },
  {
    id: 'prod-29',
    name: 'Bộ đèn thanh LED AURA Glow Bar',
    slug: 'bo-den-thanh-led-aura-glow-bar',
    sku: 'AUR-LP-29',
    category: DESK,
    price: 1490000,
    stock: 60,
    kind: 'desk',
    noun: 'đèn',
    illustrationType: 'lamp',
    isNew: true,
    createdAt: '2026-08-15T09:00:00Z',
    description:
      'Bộ hai thanh đèn LED đổi màu đặt hai bên màn hình, tạo ánh sáng nền dịu mắt cho góc làm việc và giải trí.',
    features: [
      'Bộ hai thanh, dựng đứng hoặc đặt nằm',
      '16 triệu màu, chuyển màu theo nhạc',
      'Điều khiển bằng ứng dụng hoặc nút trên thân đèn',
      'Hẹn giờ bật tắt',
    ],
    specs: {
      'Số lượng': '2 thanh',
      'Nhiệt độ màu': '2200K – 6500K và RGB',
      'Công suất': '2 x 6W',
      'Chiều cao': '29cm',
    },
    ratings: [4, 5, 4],
  },
  {
    id: 'prod-30',
    name: 'Bàn di chuột đệm cổ tay AURA Comfort',
    slug: 'ban-di-chuot-dem-co-tay-aura-comfort',
    sku: 'AUR-DM-30',
    category: DESK,
    price: 450000,
    originalPrice: 590000,
    stock: 110,
    kind: 'desk',
    noun: 'bàn di chuột',
    illustrationType: 'keyboard',
    createdAt: '2026-02-10T09:00:00Z',
    description:
      'Bàn di chuột có đệm gel đỡ cổ tay, giảm mỏi khi dùng chuột nhiều giờ liền.',
    features: [
      'Đệm gel nâng cổ tay ở tư thế tự nhiên',
      'Mặt vải mịn, di chuột chính xác',
      'Đế cao su chống trượt',
    ],
    specs: {
      'Chất liệu': 'Vải lycra, gel silicone, đế cao su',
      'Độ dày': '3mm, đệm cổ tay 20mm',
      'Kích thước': '25 x 22 cm',
    },
    ratings: [4, 3, 4, 3, 3, 4, 2, 4],
  },
  {
    id: 'prod-31',
    name: 'Tay đỡ màn hình AURA Float',
    slug: 'tay-do-man-hinh-aura-float',
    sku: 'AUR-MA-31',
    category: DESK,
    price: 1890000,
    stock: 33,
    kind: 'desk',
    noun: 'tay đỡ',
    illustrationType: 'desk',
    colors: ['Đen', 'Trắng'],
    createdAt: '2026-05-05T09:00:00Z',
    description:
      'Tay đỡ lò xo khí nâng màn hình lơ lửng trên mặt bàn, xoay ngang dọc và chỉnh độ cao chỉ bằng một tay.',
    features: [
      'Lò xo khí, chỉnh vị trí bằng một tay',
      'Xoay 360°, nghiêng và xoay dọc màn hình',
      'Đi dây gọn trong thân tay đỡ',
      'Kẹp bàn hoặc bắt xuyên mặt bàn',
    ],
    specs: {
      'Tương thích': 'Màn hình 17 – 32 inch',
      'Tải trọng': '2 – 9kg',
      'Chuẩn VESA': '75 x 75, 100 x 100',
      'Chất liệu': 'Nhôm đúc',
    },
    ratings: [4, 4, 3, 5, 4],
  },
  {
    id: 'prod-32',
    name: 'Bàn phím không dây AURA Slim 65',
    slug: 'ban-phim-khong-day-aura-slim-65',
    sku: 'AUR-KB-32',
    category: DESK,
    price: 2290000,
    stock: 55,
    kind: 'desk',
    noun: 'bàn phím',
    illustrationType: 'keyboard',
    colors: ['Xám Không Gian', 'Trắng Ngọc'],
    createdAt: '2026-07-01T09:00:00Z',
    description:
      'Bàn phím cơ mỏng với switch low-profile, vỏ nhôm và layout 65% gọn gàng cho bàn làm việc nhỏ hoặc mang theo.',
    features: [
      'Switch cơ low-profile, hành trình ngắn',
      'Vỏ nhôm mỏng 18mm',
      'Kết nối ba thiết bị qua Bluetooth',
      'Dùng được cho cả macOS và Windows',
    ],
    specs: {
      Layout: '65% (68 phím)',
      Switch: 'Low-profile Linear',
      'Kết nối': 'Bluetooth 5.1, USB-C',
      Pin: '2000mAh',
      'Trọng lượng': '540g',
    },
    ratings: [5, 4, 4, 5, 3, 4],
  },
  {
    id: 'prod-33',
    name: 'Đèn bàn cổ điển AURA Lumina Banker',
    slug: 'den-ban-co-dien-aura-lumina-banker',
    sku: 'AUR-LP-33',
    category: DESK,
    price: 4290000,
    stock: 3,
    kind: 'desk',
    noun: 'đèn',
    illustrationType: 'lamp',
    createdAt: '2026-04-28T09:00:00Z',
    description:
      'Đèn bàn kiểu ngân hàng với chao thủy tinh xanh lục và thân đồng thau, cho ánh sáng ấm tập trung xuống mặt bàn.',
    features: [
      'Chao thủy tinh xanh lục thổi thủ công',
      'Thân và đế đồng thau đúc',
      'Công tắc dây kéo',
      'Dùng bóng LED E27 thay được',
    ],
    specs: {
      'Chất liệu': 'Đồng thau, thủy tinh',
      'Đuôi đèn': 'E27',
      'Công suất tối đa': '40W',
      'Chiều cao': '38cm',
    },
    ratings: [5, 4],
  },

  // ------------------------------------------------------------ Phụ kiện cao cấp
  {
    id: 'prod-34',
    name: 'Pin dự phòng AURA PowerCore 20000',
    slug: 'pin-du-phong-aura-powercore-20000',
    sku: 'AUR-PB-34',
    category: ACCESSORY,
    price: 1190000,
    originalPrice: 1390000,
    stock: 90,
    kind: 'accessory',
    noun: 'pin dự phòng',
    illustrationType: 'hub',
    isBestSeller: true,
    colors: ['Đen', 'Trắng'],
    createdAt: '2026-03-28T09:00:00Z',
    description:
      'Pin dự phòng 20.000mAh sạc nhanh 65W, đủ sức sạc laptop và có màn hình hiển thị phần trăm pin còn lại.',
    features: [
      'Sạc nhanh 65W, sạc được laptop',
      'Ba cổng ra, sạc ba thiết bị cùng lúc',
      'Màn hình hiển thị dung lượng còn lại',
      'Được phép mang lên máy bay',
    ],
    specs: {
      'Dung lượng': '20.000mAh (74Wh)',
      'Công suất': '65W',
      'Cổng kết nối': '2x USB-C, 1x USB-A',
      'Trọng lượng': '390g',
    },
    ratings: [5, 4, 5, 4, 4, 5, 4, 3],
  },
  {
    id: 'prod-35',
    name: 'Cáp sạc bện dù AURA Link USB-C 100W',
    slug: 'cap-sac-ben-du-aura-link-usb-c-100w',
    sku: 'AUR-CB-35',
    category: ACCESSORY,
    price: 290000,
    stock: 300,
    kind: 'accessory',
    noun: 'cáp',
    illustrationType: 'hub',
    colors: ['Đen', 'Xám', 'Đỏ'],
    capacities: ['1 mét', '2 mét'],
    createdAt: '2026-02-01T09:00:00Z',
    description:
      'Cáp USB-C bện dù chịu được 30.000 lần bẻ gập, sạc nhanh 100W cho cả laptop lẫn điện thoại.',
    features: [
      'Sạc nhanh Power Delivery 100W',
      'Vỏ bện dù, chịu 30.000 lần bẻ gập',
      'Kèm dây buộc cáp bằng da',
    ],
    specs: {
      'Công suất': '100W (20V/5A)',
      'Tốc độ truyền': '480Mbps',
      'Chiều dài': '1 hoặc 2 mét',
    },
    ratings: [4, 4, 3, 5, 2, 4, 3],
  },
  {
    id: 'prod-36',
    name: 'Đế sạc không dây AURA Pad 15W',
    slug: 'de-sac-khong-day-aura-pad-15w',
    sku: 'AUR-WC-36',
    category: ACCESSORY,
    price: 1790000,
    stock: 44,
    kind: 'accessory',
    noun: 'đế sạc',
    illustrationType: 'hub',
    isNew: true,
    createdAt: '2026-08-28T09:00:00Z',
    description:
      'Đế sạc không dây mặt kính mỏng 8mm, sạc nhanh 15W cho điện thoại và tai nghe hỗ trợ chuẩn Qi.',
    features: [
      'Sạc nhanh không dây 15W',
      'Mặt kính cường lực, viền chống trượt',
      'Tự ngắt khi quá nhiệt hoặc có vật lạ',
      'Kèm cáp USB-C dài 1 mét',
    ],
    specs: {
      'Chuẩn sạc': 'Qi',
      'Công suất': '15W',
      'Cổng vào': 'USB-C',
      'Trọng lượng': '95g',
    },
    ratings: [],
  },
  {
    id: 'prod-37',
    name: 'Ổ cứng SSD di động AURA Vault',
    slug: 'o-cung-ssd-di-dong-aura-vault',
    sku: 'AUR-SD-37',
    category: ACCESSORY,
    price: 2890000,
    originalPrice: 3290000,
    stock: 36,
    kind: 'accessory',
    noun: 'ổ cứng',
    illustrationType: 'hub',
    capacities: ['1TB', '2TB'],
    createdAt: '2026-05-18T09:00:00Z',
    description:
      'Ổ SSD di động vỏ nhôm tốc độ 1050MB/s, chịu rơi từ 2 mét và mã hóa dữ liệu bằng mật khẩu.',
    features: [
      'Tốc độ đọc 1050MB/s',
      'Chịu rơi 2 mét, kháng nước IP55',
      'Mã hóa phần cứng AES 256-bit',
      'Dùng được với máy tính, điện thoại và máy chơi game',
    ],
    specs: {
      'Dung lượng': '1TB hoặc 2TB',
      'Tốc độ': '1050MB/s đọc, 1000MB/s ghi',
      'Kết nối': 'USB-C 3.2 Gen 2',
      'Trọng lượng': '52g',
    },
    ratings: [5, 5, 4, 5, 5, 4],
  },
  {
    id: 'prod-38',
    name: 'Balo công nghệ AURA Carry 20L',
    slug: 'balo-cong-nghe-aura-carry-20l',
    sku: 'AUR-BG-38',
    category: ACCESSORY,
    price: 1990000,
    stock: 52,
    kind: 'accessory',
    noun: 'balo',
    illustrationType: 'hub',
    colors: ['Đen', 'Xám Tro', 'Xanh Rêu'],
    createdAt: '2026-04-02T09:00:00Z',
    description:
      'Balo chống thấm với ngăn laptop treo chống sốc, mở phẳng 180° để qua cửa an ninh sân bay nhanh hơn.',
    features: [
      'Ngăn laptop 16 inch treo, chống sốc',
      'Vải chống thấm nước, khóa kéo YKK',
      'Mở phẳng 180°',
      'Ngăn bí mật sau lưng',
    ],
    specs: {
      'Dung tích': '20 lít',
      'Chất liệu': 'Nylon 900D phủ chống thấm',
      'Tương thích': 'Laptop đến 16 inch',
      'Trọng lượng': '980g',
    },
    ratings: [4, 5, 4, 4, 3, 5],
  },
  {
    id: 'prod-39',
    name: 'Túi chống sốc laptop AURA Sleeve',
    slug: 'tui-chong-soc-laptop-aura-sleeve',
    sku: 'AUR-SL-39',
    category: ACCESSORY,
    price: 590000,
    stock: 75,
    kind: 'accessory',
    noun: 'túi',
    illustrationType: 'hub',
    colors: ['Xám Nỉ', 'Đen'],
    capacities: ['13 – 14 inch', '15 – 16 inch'],
    createdAt: '2026-01-22T09:00:00Z',
    description:
      'Túi nỉ lót lông mịn ôm sát laptop, có ngăn phụ cho sạc và chuột.',
    features: [
      'Lót lông mịn chống xước',
      'Ngăn phụ cho sạc và chuột',
      'Nắp cài nam châm',
    ],
    specs: {
      'Chất liệu': 'Nỉ và da tổng hợp',
      'Kích cỡ': '13 – 14 inch hoặc 15 – 16 inch',
      'Trọng lượng': '210g',
    },
    ratings: [3, 2, 3, 4, 2, 3],
  },
  {
    id: 'prod-40',
    name: 'Webcam AURA Meet 4K',
    slug: 'webcam-aura-meet-4k',
    sku: 'AUR-WB-40',
    category: ACCESSORY,
    price: 2490000,
    stock: 30,
    kind: 'accessory',
    noun: 'webcam',
    illustrationType: 'camera',
    createdAt: '2026-06-14T09:00:00Z',
    description:
      'Webcam 4K tự lấy nét và tự giữ bạn ở giữa khung hình, với hai micro lọc ồn và nắp che ống kính.',
    features: [
      'Cảm biến 4K, quay 1080p ở 60 khung hình/giây',
      'Tự lấy nét và tự căn khung hình',
      'Hai micro lọc tiếng ồn',
      'Nắp trượt che ống kính',
    ],
    specs: {
      'Độ phân giải': '4K 30fps, 1080p 60fps',
      'Góc nhìn': '90°',
      'Kết nối': 'USB-C',
      Micro: '2 micro đa hướng',
    },
    ratings: [4, 4, 5, 3],
  },

  // --------------------------------------------------------- Gia dụng thông minh
  {
    id: 'prod-41',
    name: 'Robot hút bụi lau nhà AURA Sweep S8',
    slug: 'robot-hut-bui-lau-nha-aura-sweep-s8',
    sku: 'AUR-RV-41',
    category: HOME,
    price: 10900000,
    originalPrice: 12900000,
    stock: 16,
    kind: 'home',
    noun: 'robot',
    illustrationType: 'camera',
    badge: 'Bán chạy',
    isFeatured: true,
    isBestSeller: true,
    colors: ['Trắng', 'Đen'],
    createdAt: '2026-05-08T09:00:00Z',
    description:
      'Robot hút và lau kết hợp, dẫn đường bằng laser, tự nhấc giẻ khi lên thảm và tự đổ rác về trạm.',
    features: [
      'Lực hút 6000Pa, tự tăng lực trên thảm',
      'Dẫn đường laser, vẽ bản đồ nhiều tầng',
      'Trạm tự đổ rác, dùng 60 ngày mới phải thay túi',
      'Tránh dây điện và đồ vật nhỏ bằng camera',
    ],
    specs: {
      'Lực hút': '6000Pa',
      Pin: '5200mAh, chạy 180 phút',
      'Dẫn đường': 'LiDAR + camera',
      'Hộp bụi': '400ml, túi trạm 2.5 lít',
      'Độ ồn': '65dB',
    },
    ratings: [5, 4, 4, 5, 4, 3, 4, 5],
  },
  {
    id: 'prod-42',
    name: 'Máy lọc không khí AURA Breeze',
    slug: 'may-loc-khong-khi-aura-breeze',
    sku: 'AUR-AP-42',
    category: HOME,
    price: 5490000,
    stock: 25,
    kind: 'home',
    noun: 'máy lọc',
    illustrationType: 'camera',
    createdAt: '2026-04-16T09:00:00Z',
    description:
      'Máy lọc không khí cho phòng đến 45m², màng lọc HEPA H13 và cảm biến bụi mịn hiển thị chất lượng không khí theo thời gian thực.',
    features: [
      'Màng lọc HEPA H13, giữ 99,97% bụi mịn',
      'Cảm biến PM2.5 hiển thị theo thời gian thực',
      'Chế độ ngủ chỉ 22dB',
      'Điều khiển và hẹn giờ qua ứng dụng',
    ],
    specs: {
      'Diện tích phòng': 'Đến 45m²',
      'Lưu lượng khí sạch': '380m³/giờ',
      'Màng lọc': 'HEPA H13 + than hoạt tính',
      'Độ ồn': '22 – 58dB',
      'Công suất': '38W',
    },
    ratings: [5, 4, 4, 5, 4],
  },
  {
    id: 'prod-43',
    name: 'Bóng đèn thông minh AURA Glow',
    slug: 'bong-den-thong-minh-aura-glow',
    sku: 'AUR-BL-43',
    category: HOME,
    price: 290000,
    originalPrice: 350000,
    stock: 250,
    kind: 'home',
    noun: 'bóng đèn',
    illustrationType: 'lamp',
    capacities: ['1 bóng', 'Bộ 3 bóng'],
    createdAt: '2026-01-30T09:00:00Z',
    description:
      'Bóng đèn đuôi E27 đổi 16 triệu màu, hẹn giờ và điều khiển bằng giọng nói, không cần bộ trung tâm.',
    features: [
      '16 triệu màu và ánh sáng trắng chỉnh được',
      'Kết nối Wi-Fi trực tiếp, không cần bộ trung tâm',
      'Hẹn giờ bật tắt, giả lập có người ở nhà',
      'Tương thích trợ lý giọng nói',
    ],
    specs: {
      'Đuôi đèn': 'E27',
      'Công suất': '9W (tương đương 60W)',
      'Quang thông': '806 lumen',
      'Kết nối': 'Wi-Fi 2.4GHz, Bluetooth',
    },
    ratings: [4, 3, 4, 4, 3, 5, 3, 4, 2],
  },
  {
    id: 'prod-44',
    name: 'Ổ cắm thông minh AURA Plug',
    slug: 'o-cam-thong-minh-aura-plug',
    sku: 'AUR-PL-44',
    category: HOME,
    price: 350000,
    stock: 180,
    kind: 'home',
    noun: 'ổ cắm',
    illustrationType: 'hub',
    createdAt: '2026-02-18T09:00:00Z',
    description:
      'Ổ cắm Wi-Fi biến thiết bị thường thành thiết bị thông minh: bật tắt từ xa, hẹn giờ và đo điện năng tiêu thụ.',
    features: [
      'Bật tắt từ xa qua ứng dụng',
      'Đo điện năng tiêu thụ theo ngày và tháng',
      'Hẹn giờ và đếm ngược',
      'Tự ngắt khi quá tải',
    ],
    specs: {
      'Tải tối đa': '16A / 3500W',
      'Kết nối': 'Wi-Fi 2.4GHz',
      'Chuẩn chân cắm': 'Đa năng',
    },
    ratings: [3, 4, 2, 3, 3, 2, 4],
  },
  {
    id: 'prod-45',
    name: 'Chuông cửa có hình AURA Door',
    slug: 'chuong-cua-co-hinh-aura-door',
    sku: 'AUR-DB-45',
    category: HOME,
    price: 2290000,
    stock: 28,
    kind: 'home',
    noun: 'chuông cửa',
    illustrationType: 'camera',
    createdAt: '2026-06-06T09:00:00Z',
    description:
      'Chuông cửa camera 2K dùng pin, báo về điện thoại khi có người bấm chuông hoặc đứng trước cửa và cho phép trò chuyện hai chiều.',
    features: [
      'Camera 2K góc rộng, thấy trọn người đứng trước cửa',
      'Đàm thoại hai chiều qua điện thoại',
      'Dùng pin 6 tháng, không cần đi dây',
      'Lưu video trên thẻ nhớ, không mất phí hàng tháng',
    ],
    specs: {
      'Độ phân giải': '2K (2560 x 1920)',
      'Góc nhìn': '160°',
      Pin: '5000mAh',
      'Chống nước': 'IP65',
      'Lưu trữ': 'Thẻ microSD đến 256GB',
    },
    ratings: [4, 4, 3, 4, 5],
  },
  {
    id: 'prod-46',
    name: 'Khóa cửa thông minh AURA Lock',
    slug: 'khoa-cua-thong-minh-aura-lock',
    sku: 'AUR-LK-46',
    category: HOME,
    price: 6900000,
    originalPrice: 7900000,
    stock: 11,
    kind: 'home',
    noun: 'khóa',
    illustrationType: 'camera',
    colors: ['Đen', 'Đồng'],
    createdAt: '2026-07-12T09:00:00Z',
    description:
      'Khóa cửa mở bằng vân tay, mã số, thẻ từ hoặc điện thoại, với chìa cơ dự phòng và cổng sạc khẩn cấp khi hết pin.',
    features: [
      'Năm cách mở: vân tay, mã số, thẻ, ứng dụng, chìa cơ',
      'Nhận diện vân tay trong 0,3 giây',
      'Cấp mã tạm thời cho khách từ xa',
      'Cảnh báo khi cửa chưa đóng hoặc nhập sai nhiều lần',
    ],
    specs: {
      'Chất liệu': 'Hợp kim kẽm',
      'Độ dày cửa': '38 – 90mm',
      Pin: '8 pin AA, dùng 12 tháng',
      'Kết nối': 'Bluetooth, Wi-Fi qua gateway',
      'Dung lượng': '100 vân tay, 50 mã số',
    },
    ratings: [5, 4, 5, 4],
  },
  {
    id: 'prod-47',
    name: 'Máy pha cà phê AURA Brew Espresso',
    slug: 'may-pha-ca-phe-aura-brew-espresso',
    sku: 'AUR-CF-47',
    category: HOME,
    price: 8490000,
    stock: 9,
    kind: 'home',
    noun: 'máy pha',
    illustrationType: 'camera',
    badge: 'Cho người mê cà phê',
    colors: ['Thép Không Gỉ', 'Đen Mờ'],
    createdAt: '2026-03-10T09:00:00Z',
    description:
      'Máy pha espresso bán tự động áp suất 15 bar, làm nóng trong 25 giây, kèm cần đánh sữa cho cappuccino tại nhà.',
    features: [
      'Bơm áp suất 15 bar',
      'Làm nóng trong 25 giây',
      'Cần đánh sữa bằng hơi',
      'Kiểm soát nhiệt độ PID, chính xác đến 1°C',
    ],
    specs: {
      'Áp suất': '15 bar',
      'Bình nước': '1.8 lít',
      'Công suất': '1450W',
      'Tay pha': '54mm',
      'Trọng lượng': '7.2kg',
    },
    ratings: [5, 5, 4, 4, 5],
  },
  {
    id: 'prod-48',
    name: 'Máy tạo ẩm AURA Mist',
    slug: 'may-tao-am-aura-mist',
    sku: 'AUR-HM-48',
    category: HOME,
    price: 1290000,
    stock: 64,
    kind: 'home',
    noun: 'máy tạo ẩm',
    illustrationType: 'lamp',
    colors: ['Trắng'],
    createdAt: '2026-05-22T09:00:00Z',
    description:
      'Máy tạo ẩm siêu âm châm nước từ trên, chạy êm suốt đêm và tự ngắt khi hết nước.',
    features: [
      'Châm nước từ trên, không cần tháo bình',
      'Chạy êm dưới 30dB',
      'Tự ngắt khi hết nước',
      'Bình 4 lít dùng 30 giờ',
    ],
    specs: {
      'Dung tích': '4 lít',
      'Công suất phun': '300ml/giờ',
      'Diện tích phòng': 'Đến 30m²',
      'Độ ồn': 'Dưới 30dB',
    },
    ratings: [3, 4, 3, 2, 4, 3],
  },
  {
    id: 'prod-49',
    name: 'Ấm siêu tốc giữ nhiệt AURA Kettle',
    slug: 'am-sieu-toc-giu-nhiet-aura-kettle',
    sku: 'AUR-KT-49',
    category: HOME,
    price: 1490000,
    stock: 48,
    kind: 'home',
    noun: 'ấm',
    illustrationType: 'lamp',
    isNew: true,
    colors: ['Đen Mờ', 'Trắng Kem'],
    createdAt: '2026-09-05T09:00:00Z',
    description:
      'Ấm đun vòi cổ ngỗng cho người pha trà và cà phê thủ công: chọn nhiệt độ chính xác đến từng độ và giữ ấm 60 phút.',
    features: [
      'Chọn nhiệt độ từ 40 đến 100°C',
      'Vòi cổ ngỗng, rót đều tay',
      'Giữ ấm 60 phút',
      'Lòng ấm thép không gỉ 304',
    ],
    specs: {
      'Dung tích': '0.9 lít',
      'Công suất': '1200W',
      'Nhiệt độ': '40 – 100°C',
      'Chất liệu': 'Thép không gỉ 304',
    },
    ratings: [],
  },
];
